version: '3'

services:
#  app:
#    container_name: "eventBuddy-app"
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - 8080:8080
#    environment:
#      DB_USER: ${DB_USER}
#      DB_PASSWORD: ${DB_PASSWORD}
#      DB_NAME: ${POSTGRES_DB}
#      DB_HOST: eventBuddy_db
#      DB_PORT: 5432

  eventBuddy-db:
    container_name: eventBuddy-db
    image: postgres:16
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - eventBuddy-db:/var/lib/postgresql/data
#      - ./db/init-scripts.sql:/docker-entrypoint-initdb.d/scripts.sql
volumes:
  eventBuddy-db:
#    external: true